#!/bin/bash
 
# Boot a qemu virtual machine using qcow2 and iso files 
# in current working directory.
#
# Note that `-monitor stdio` pipes the qemu monitor to standard terminal output.
# normally the qemu monitor is accessed from within the qemu window itself.
# This allows all qemu monitor interaction to be done from the command line.
#
# To save the state of your VM, first create a file named `vm-name` and add 
# the name you will save your VM as. Anytime you wish to save your VM,
# type `savevm <name>` on the commandline you booted qemu from. 
# 
# To load the saved VM, just run the script: `./boot-vm`.

QCOW2_FILE="./*.qcow2"
ISO_FILE="./*.iso"
VM_NAME=$(cat ./vm-name)

qemu-system-x86_64 \
    # Emulated machine and accelerator;
    # HVF is MacOS native hypervisor
    -machine type=q35,accel=hvf \
    # number of CPU's
    -smp 2 \
    # disk drive 
    -hda $QCOW2_FILE \
    # iso image to put into CD drive
    -cdrom $ISO_FILE \
    # amount of memory
    -m 4G \
    # graphics card to use
    -vga virtio \
    # enable usb host controller
    -usb \
    # mouse doesn't work without
    -device usb-tablet \
    # show mouse cursor
    -display default,show-cursor=on \
    # pipe qemu monitor to standard output
    -monitor stdio \
    # load virtual machine saved as name 
    # in specified `./vm-name`
    -loadvm $VM_NAME
